version: '3'

services:
  db:
    image: postgres:16-alpine
    container_name: dev_postgres
    ports:
      - "5433:5432"
    env_file: .env.compose
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  web:
    build: .
    container_name: dev_django
    command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file: .env.compose
    depends_on:
      - db
      - redis
    volumes:
      - .:/app


  redis:
    image: redis:7
    container_name: dev_redis
    ports:
      - "6380:6379"

  celery:
    build: .
    container_name: dev_celery
    command: celery -A __project__ worker -l info
    env_file: .env.compose
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

volumes:
  postgres_data:
