# Generated by Django 5.2.8 on 2025-11-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок задачи', max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Описание задачи (необязательно)', null=True, verbose_name='Description')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Completed')], db_index=True, default=1, help_text='Статус задачи', verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания задачи', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Время последнего обновления задачи', verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
