# Generated by Django 5.2.8 on 2025-11-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Completed')], db_index=True, default=0, help_text='Статус задачи', verbose_name='Status'),
        ),
    ]
